// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

package configs

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/foundriesio/dg-satellite/cli/api"
)

var appliedCmd = &cobra.Command{
	Use:   "applied <device-uuid>",
	Short: "Show the applied configuration for a device",
	Long: `Show the merged (factory + group + device) configuration that was most
recently delivered to the device, along with the time it was applied.`,
	Args: cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		a := api.CtxGetApi(cmd.Context()).Configs().Device(args[0])
		getDeviceApplied(a)
	},
}

func init() {
	ConfigsCmd.AddCommand(appliedCmd)
}

func getDeviceApplied(a api.DeviceConfigsApi) {
	cfg, err := a.GetApplied()
	cobra.CheckErr(err)
	if cfg.AppliedAt == 0 {
		fmt.Println("No configuration has been applied to this device yet.")
		return
	}
	fmt.Printf("Applied at: %s\n", formatTimestamp(cfg.AppliedAt))
	printAuditFields(cfg)
	printConfigs(cfg.Files)
}

func printAuditFields(cfg api.AppliedConfigs) {
	msg := func(s string) string {
		if len(s) > 0 {
			s = ": " + s
		}
		return s
	}
	fmt.Println("Generated by auto-merging the following configs:")
	if a := cfg.AuditTrail[0]; a.CreatedAt > 0 {
		fmt.Printf("\tGlobal config created by %s at %s%s\n",
			a.CreatedBy, formatTimestamp(a.CreatedAt), msg(a.Reason))
	}
	if a := cfg.AuditTrail[1]; a.CreatedAt > 0 {
		fmt.Printf("\tGroup config created by %s at %s%s\n",
			a.CreatedBy, formatTimestamp(a.CreatedAt), msg(a.Reason))
	}
	if a := cfg.AuditTrail[2]; a.CreatedAt > 0 {
		fmt.Printf("\tDevice config created by %s at %s%s\n",
			a.CreatedBy, formatTimestamp(a.CreatedAt), msg(a.Reason))
	}
}
