services:
  locust:
    build:
      context: ../..
      dockerfile: ./contrib/scale-test/Dockerfile
    command:
      - /contrib/scale-test/locust.sh
      - --datadir
      - /data
      - --num-devices
      - "${NUM_DEVICES:-5000}"
      - --locustfile
      - ${LOCUSTFILE}
    volumes:
      - ../../contrib:/contrib
      - ${DATA_DIR:-./scale-test-data}:/data
    ports:
      - "8089:8089" # Locust web UI

  dg-sat:
    build:
      context: ../..
      dockerfile: ./contrib/scale-test/Dockerfile
    command:
      - dg-sat
      - --datadir
      - /data
      - serve
    volumes:
      - ${DATA_DIR:-./scale-test-data}:/data
