FROM public.ecr.aws/docker/library/golang:1.25-bookworm

RUN --mount=target=/ctx \
    if [ -d /ctx/.extra-certs/ ] ; then \
        cp /ctx/.extra-certs/* /usr/local/share/ca-certificates/ && update-ca-certificates; \
    fi

RUN \
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6 \
    && golangci-lint --version
