// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

package api

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/foundriesio/update-server/storage"
	"github.com/foundriesio/update-server/storage/gateway"
	storageTesting "github.com/foundriesio/update-server/storage/testing"
	"github.com/foundriesio/update-server/storage/tuf"
)

func TestCreateUpdateGeneratesTufFromApps(t *testing.T) {
	s := newTufStorage(t) // TUF is initialized and loaded -> enabled.

	// An upload with apps but no "tuf" directory should have its TUF metadata
	// generated by the server.
	tar := storageTesting.CreateTarBuffer(t, map[string]string{
		"apps/apps/shellhttpd/sha256appcontenthash": "{}",
	})
	opts := TargetOptions{Name: "my-app-target", HardwareId: "generic-x86-64", BaseUrl: "https://sat.example.com"}
	require.NoError(t, s.CreateUpdate("main", "v1.0", "tester", opts, tar))

	// Targets metadata was generated for the update.
	var targets tuf.AtsTufTargets
	require.NoError(t, s.fs.Tuf.ReadTufMeta("main", "v1.0", storage.TufTargetsFile, &targets))
	require.Len(t, targets.Signed.Targets, 1)

	target, ok := targets.Signed.Targets["my-app-target-1"]
	require.True(t, ok, "expected generated target keyed by name and version")

	var custom generatedTargetCustom
	require.NoError(t, json.Unmarshal(target.Custom, &custom))
	require.Len(t, custom.DockerComposeApps, 1)
	assert.Equal(t, "https://sat.example.com/composeapphack/shellhttpd@sha256:sha256appcontenthash",
		custom.DockerComposeApps["shellhttpd"].URI)

	// The update was registered in the database.
	updates, err := s.ListUpdates("main")
	require.NoError(t, err)
	require.Len(t, updates["main"], 1)
	assert.Equal(t, "v1.0", updates["main"][0].Name)
}

func TestCreateUpdateUsesUploadedTuf(t *testing.T) {
	s := newTufStorage(t)

	// An upload that includes a valid tuf directory is stored as-is and is not
	// regenerated by the server.
	validTargets := `{"signed": {"targets": {"foo": {"custom": {"tags": ["main"]}}}}}`
	tar := storageTesting.CreateTarBuffer(t, map[string]string{
		"tuf/root.json":      `{"signed":{}}`,
		"tuf/targets.json":   validTargets,
		"ostree_repo/config": "[core]\n",
	})
	require.NoError(t, s.CreateUpdate("main", "v1.0", "tester", TargetOptions{}, tar))

	raw, err := s.fs.Updates.Tuf.ReadFile("main", "v1.0", storage.TufTargetsFile)
	require.NoError(t, err)
	assert.JSONEq(t, validTargets, raw)
}

func TestListUpdatesDeviceCount(t *testing.T) {
	tmpdir := t.TempDir()
	dbFile := filepath.Join(tmpdir, "sql.db")
	db, err := storage.NewDb(dbFile)
	require.NoError(t, err)
	fs, err := storage.NewFs(tmpdir)
	require.NoError(t, err)

	s, err := NewStorage(db, fs)
	require.NoError(t, err)

	dg, err := gateway.NewStorage(db, fs)
	require.NoError(t, err)

	// Seed updates: two on "main", one on "dev".
	require.NoError(t, s.InsertUpdate("main", "v1.0", "tester"))
	require.NoError(t, s.InsertUpdate("main", "v2.0", "tester"))
	require.NoError(t, s.InsertUpdate("dev", "v1.0", "tester"))

	// Create and check in devices on the "main" tag.
	for _, uuid := range []string{"uuid-1", "uuid-2", "uuid-3", "uuid-4"} {
		d, err := dg.DeviceCreate(uuid, "pubkey-"+uuid)
		require.NoError(t, err)
		require.NoError(t, d.CheckIn("target", "main", "hash", ""))
	}

	// Assign two devices to v1.0 and one to v2.0.
	assigned, err := s.SetUpdateName("main", "v1.0", []string{"uuid-1", "uuid-2"}, nil)
	require.NoError(t, err)
	require.Len(t, assigned, 2)
	assigned, err = s.SetUpdateName("main", "v2.0", []string{"uuid-3"}, nil)
	require.NoError(t, err)
	require.Len(t, assigned, 1)

	// Assign uuid-4 to v1.0 then delete it: deleted devices must not be counted.
	assigned, err = s.SetUpdateName("main", "v1.0", []string{"uuid-4"}, nil)
	require.NoError(t, err)
	require.Len(t, assigned, 1)
	d, err := s.DeviceGet("uuid-4")
	require.NoError(t, err)
	require.NoError(t, d.Delete())

	updates, err := s.ListUpdates("main")
	require.NoError(t, err)
	require.Len(t, updates["main"], 2)

	counts := map[string]int{}
	for _, u := range updates["main"] {
		counts[u.Name] = u.DeviceCount
	}
	assert.Equal(t, 2, counts["v1.0"], "v1.0 should count only its two non-deleted devices")
	assert.Equal(t, 1, counts["v2.0"], "v2.0 should count its single assigned device")

	// An update with no assigned devices reports a count of zero.
	all, err := s.ListUpdates("")
	require.NoError(t, err)
	require.Len(t, all["dev"], 1)
	assert.Equal(t, "v1.0", all["dev"][0].Name)
	assert.Equal(t, 0, all["dev"][0].DeviceCount)
}

func TestDeleteUpdate(t *testing.T) {
	tmpdir := t.TempDir()
	dbFile := filepath.Join(tmpdir, "sql.db")
	db, err := storage.NewDb(dbFile)
	require.NoError(t, err)
	fs, err := storage.NewFs(tmpdir)
	require.NoError(t, err)

	s, err := NewStorage(db, fs)
	require.NoError(t, err)

	dg, err := gateway.NewStorage(db, fs)
	require.NoError(t, err)

	// Deleting a non-existent update (unknown tag) returns ErrNotExist.
	err = s.DeleteUpdate("main", "v1.0")
	require.ErrorIs(t, err, os.ErrNotExist)

	// Seed an update with an on-disk directory.
	require.NoError(t, s.InsertUpdate("main", "v1.0", "tester"))
	require.NoError(t, s.fs.Updates.Tuf.WriteFile("main", "v1.0", storage.TufTargetsFile, "{}"))

	// Deleting a non-existent name within an existing tag returns ErrNotExist.
	err = s.DeleteUpdate("main", "v2.0")
	require.ErrorIs(t, err, os.ErrNotExist)

	// An update with an assigned device cannot be deleted.
	d, err := dg.DeviceCreate("uuid-1", "pubkey-1")
	require.NoError(t, err)
	require.NoError(t, d.CheckIn("target", "main", "hash", ""))
	assigned, err := s.SetUpdateName("main", "v1.0", []string{"uuid-1"}, nil)
	require.NoError(t, err)
	require.Len(t, assigned, 1)

	err = s.DeleteUpdate("main", "v1.0")
	require.ErrorIs(t, err, ErrUpdateInUse)

	// The update and its files still exist after a refused delete.
	updates, err := s.ListUpdates("main")
	require.NoError(t, err)
	require.Len(t, updates["main"], 1)
	_, err = s.fs.Updates.Tuf.ReadFile("main", "v1.0", storage.TufTargetsFile)
	require.NoError(t, err)

	// Once no non-deleted device is assigned, the update can be deleted.
	dev, err := s.DeviceGet("uuid-1")
	require.NoError(t, err)
	require.NoError(t, dev.Delete())
	require.NoError(t, s.DeleteUpdate("main", "v1.0"))

	// The database row is gone.
	updates, err = s.ListUpdates("main")
	require.NoError(t, err)
	require.Empty(t, updates["main"])

	// The on-disk directory is gone.
	_, err = s.fs.Updates.Tuf.ReadFile("main", "v1.0", storage.TufTargetsFile)
	require.True(t, errors.Is(err, os.ErrNotExist), "expected update files to be removed, got %v", err)

	// Deleting an already-deleted update returns ErrNotExist.
	err = s.DeleteUpdate("main", "v1.0")
	require.ErrorIs(t, err, os.ErrNotExist)
}
