// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

package api

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/foundriesio/update-server/storage"
	storageTesting "github.com/foundriesio/update-server/storage/testing"
	"github.com/foundriesio/update-server/storage/tuf"
)

func TestCreateUpdateGeneratesTufFromApps(t *testing.T) {
	s := newTufStorage(t) // TUF is initialized and loaded -> enabled.

	// An upload with apps but no "tuf" directory should have its TUF metadata
	// generated by the server.
	tar := storageTesting.CreateTarBuffer(t, map[string]string{
		"apps/apps/shellhttpd/sha256appcontenthash": "{}",
	})
	opts := TargetOptions{Name: "my-app-target", HardwareId: "generic-x86-64", BaseUrl: "https://sat.example.com"}
	require.NoError(t, s.CreateUpdate("main", "v1.0", "tester", opts, tar))

	// Targets metadata was generated for the update.
	var targets tuf.AtsTufTargets
	require.NoError(t, s.fs.Tuf.ReadTufMeta("main", "v1.0", storage.TufTargetsFile, &targets))
	require.Len(t, targets.Signed.Targets, 1)

	target, ok := targets.Signed.Targets["my-app-target-0"]
	require.True(t, ok, "expected generated target keyed by name and version")

	var custom generatedTargetCustom
	require.NoError(t, json.Unmarshal(target.Custom, &custom))
	require.Len(t, custom.DockerComposeApps, 1)
	assert.Equal(t, "https://sat.example.com/composeapphack/shellhttpd@sha256:sha256appcontenthash",
		custom.DockerComposeApps["shellhttpd"].URI)

	// The update was registered in the database.
	updates, err := s.ListUpdates("main")
	require.NoError(t, err)
	require.Len(t, updates["main"], 1)
	assert.Equal(t, "v1.0", updates["main"][0].Name)
}

func TestCreateUpdateUsesUploadedTuf(t *testing.T) {
	s := newTufStorage(t)

	// An upload that includes a valid tuf directory is stored as-is and is not
	// regenerated by the server.
	validTargets := `{"signed": {"targets": {"foo": {"custom": {"tags": ["main"]}}}}}`
	tar := storageTesting.CreateTarBuffer(t, map[string]string{
		"tuf/root.json":      `{"signed":{}}`,
		"tuf/targets.json":   validTargets,
		"ostree_repo/config": "[core]\n",
	})
	require.NoError(t, s.CreateUpdate("main", "v1.0", "tester", TargetOptions{}, tar))

	raw, err := s.fs.Updates.Tuf.ReadFile("main", "v1.0", storage.TufTargetsFile)
	require.NoError(t, err)
	assert.JSONEq(t, validTargets, raw)
}
