version: "2"
run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 80
  max-same-issues: 30

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dupl
    - errcheck
    - errorlint
    - exptostd
    - gocheckcompilerdirectives
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
  settings:
    lll:
      line-length: 200
    nolintlint:
      require-specific: true
formatters:
  enable:
    - gofmt
    - goimports
