FROM golang:alpine AS builder

RUN apk add --no-cache git make
RUN git clone https://github.com/foundriesio/fioup
RUN cd fioup && make build

FROM docker:dind
COPY --from=builder /go/fioup/bin/fioup /usr/local/bin/fioup