name: Post merge check
on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build environment
        run: |
           cd contrib/e2e
           make build

      - name: Run tests
        run: |
           cd contrib/e2e
           make run