name: Unit Test
on:
  pull_request:

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  lint:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.24'
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          wget -O gotestsum.tgz https://github.com/gotestyourself/gotestsum/releases/download/v1.13.0/gotestsum_1.13.0_linux_amd64.tar.gz
          tar -xf gotestsum.tgz
          echo "524bb9d2639f87bdb76db4b32e3b09e0838eec8a5da73c4d30ea2bedc22cf1d7 gotestsum" | sha256sum --check

          ./gotestsum

  swagger:
    name: swagger-docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Generate Swagger docs
        run: make swagger
